package View;

import Controller.Principal;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import util.Formata;

public class CadastroPaciente extends javax.swing.JFrame {

    private void registrarMedico(){
        if(tfSexoMedico.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Há campos vazios");
        } else if (tfSnMedico.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Há campos vazios");
        } else if (tfNmMedico.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Há campos vazios");
        } else if (tffCpfMedico.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Há campos vazios");
        } else if (tftCRM.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Há campos vazios");
        } else if (tffDtMedico.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Há campos vazios");
        } else if (tffTelefoneMedico.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Há campos vazios");
        } else {
            String nome = tfNmMedico.getText();
            String sobrenome = tfSnMedico.getText();
            String CRM = tftCRM.getText();
            String CPF = tffCpfMedico.getText();
            String Nascimento = tffDtMedico.getText();
            String Telefone = tffTelefoneMedico.getText();
            String estadocivil = cbEstadoCivilMedico.getSelectedItem().toString();
            String Sexo = tfSexoMedico.getText();
            
            Principal r = new Principal();
            r.registrarMedico(nome, sobrenome, CRM, CPF, Nascimento, Telefone, estadocivil, Sexo);
        }
    }
    
    private void registrarPaciente(){
        
    }
    
    private void setMask(){
        tffCpfMedico.setFormatterFactory(Formata.cpf());
        tffCpf.setFormatterFactory(Formata.cpf());
        tffTelefonePaciente.setFormatterFactory(Formata.telefone());
        tffTelefoneMedico.setFormatterFactory(Formata.telefone());
        tffDtMedico.setFormatterFactory(Formata.DtNascimento());
        tffDtPaciente.setFormatterFactory(Formata.DtNascimento());
    }
    
    private void LimpaMed(){
        tfSexoMedico.setText("");
        tfSnMedico.setText("");
        tfNmMedico.setText("");
        tffCpfMedico.setText("");
        tftCRM.setText("");
        tffDtMedico.setText("");
        tffTelefoneMedico.setText("");
        tfSexoMedico.requestFocus();
    }
    
    private void LimpaPaciente(){
        tfSexoMedico.setText("");
        tfSnMedico.setText("");
        tfNmMedico.setText("");
        tffCpfMedico.setText("");
        tftCRM.setText("");
        tffDtMedico.setText("");
        tffTelefoneMedico.setText("");
        tfSexoMedico.requestFocus();
    }
    
    
    /**
     * Creates new form CadastroPaciente
     */
    public CadastroPaciente() {
        initComponents();
        setMask();
    }
    public void tff(){

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        tbCadastros = new javax.swing.JTabbedPane();
        pnPaciente = new javax.swing.JPanel();
        tffDtPaciente = new javax.swing.JFormattedTextField();
        lblDataNascimento = new javax.swing.JLabel();
        tfSexoPaciente = new javax.swing.JTextField();
        lblSexoPaciente = new javax.swing.JLabel();
        tffCpf = new javax.swing.JFormattedTextField();
        lblCpf = new javax.swing.JLabel();
        tfNmPaciente = new javax.swing.JTextField();
        lblNmPaciente = new javax.swing.JLabel();
        tffTelefonePaciente = new javax.swing.JFormattedTextField();
        lblTelefone = new javax.swing.JLabel();
        cbEstadoCivil = new javax.swing.JComboBox<>();
        lblEstadoCivil = new javax.swing.JLabel();
        cbConvenio = new javax.swing.JComboBox<>();
        lblConvenio = new javax.swing.JLabel();
        lbPacientes = new javax.swing.JLabel();
        tfSnPaciente = new javax.swing.JTextField();
        lblSnPaciente = new javax.swing.JLabel();
        pnMedico = new javax.swing.JPanel();
        tfSexoMedico = new javax.swing.JTextField();
        tfNmMedico = new javax.swing.JTextField();
        tffCpfMedico = new javax.swing.JFormattedTextField();
        tffDtMedico = new javax.swing.JFormattedTextField();
        tffTelefoneMedico = new javax.swing.JFormattedTextField();
        cbEstadoCivilMedico = new javax.swing.JComboBox<>();
        cbEspecialidade = new javax.swing.JComboBox<>();
        lblEspecialidade = new javax.swing.JLabel();
        lblEstadoCivil1 = new javax.swing.JLabel();
        lblTelefone1 = new javax.swing.JLabel();
        lblDataNascimento1 = new javax.swing.JLabel();
        lblcdMedico = new javax.swing.JLabel();
        lblNmMedico = new javax.swing.JLabel();
        lblCpf1 = new javax.swing.JLabel();
        lblCRM = new javax.swing.JLabel();
        tftCRM = new javax.swing.JFormattedTextField();
        lbMedicos = new javax.swing.JLabel();
        tfSnMedico = new javax.swing.JTextField();
        lblSnMedico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setText("Cadastros");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblDataNascimento.setText("Data de nascimento");

        lblSexoPaciente.setText("Sexo do Paciente");

        tffCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        lblCpf.setText("Cpf");

        lblNmPaciente.setText("Nome");

        lblTelefone.setText("Telefone");

        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)", "Separado(a)" }));

        lblEstadoCivil.setText("Estado civil");

        cbConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amil", "NotreDame Intermédica", "Item 3", "Item 4" }));

        lblConvenio.setText("Convenio");

        lbPacientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPacientes.setText("Pacientes");

        lblSnPaciente.setText("Sobrenome");

        javax.swing.GroupLayout pnPacienteLayout = new javax.swing.GroupLayout(pnPaciente);
        pnPaciente.setLayout(pnPacienteLayout);
        pnPacienteLayout.setHorizontalGroup(
            pnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPacienteLayout.createSequentialGroup()
                        .addComponent(tffDtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tffTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPacienteLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(cbConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPacienteLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(lblConvenio))))
                    .addGroup(pnPacienteLayout.createSequentialGroup()
                        .addComponent(lblDataNascimento)
                        .addGap(57, 57, 57)
                        .addComponent(lblTelefone)
                        .addGap(65, 65, 65)
                        .addComponent(lblEstadoCivil))
                    .addGroup(pnPacienteLayout.createSequentialGroup()
                        .addGroup(pnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPacienteLayout.createSequentialGroup()
                                .addComponent(tfSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(pnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNmPaciente)
                                    .addComponent(tfNmPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblSexoPaciente))
                        .addGap(13, 13, 13)
                        .addGroup(pnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPacienteLayout.createSequentialGroup()
                                .addComponent(lblSnPaciente)
                                .addGap(71, 71, 71)
                                .addComponent(lblCpf))
                            .addGroup(pnPacienteLayout.createSequentialGroup()
                                .addGroup(pnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbPacientes)
                                    .addComponent(tfSnPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(tffCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        pnPacienteLayout.setVerticalGroup(
            pnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPacientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(pnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexoPaciente)
                    .addComponent(lblCpf)
                    .addComponent(lblNmPaciente)
                    .addComponent(lblSnPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tffCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNmPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSnPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascimento)
                    .addComponent(lblTelefone)
                    .addComponent(lblEstadoCivil)
                    .addComponent(lblConvenio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tffDtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tffTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbCadastros.addTab("Paciente", pnPaciente);

        tffCpfMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        cbEstadoCivilMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)", "Separado(a)" }));

        cbEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alergia/Imunologia", "Angiologia", "Cardiologia", "Cirurgia Geral", "Cirurgia Pediátrica", "Cirurgia Plástica", "Clínica Médica", "Dermatologia", "Doenças Infecto-Parasitárias", "DST/AIDS (Doenças Sexualmente Transmissíveis/AIDS)", "Endocrinologia", "Fisiatria/Medicina Esportiva", "Fonoaudiologia", "Gastroenterologia", "Genética", "Geral", "Geriatria", "Ginecologia", "Hematologia", "Homeopatia, Acupuntura e Similares", "Medicina Preventiva e Social", "Medicina do Trabalho", "Nefrologia", "Neurologia", "Nutrição e Dietética", "Obstetrícia", "Odontologia", "Oftalmologia", "Oncologia", "Ortopedia e Traumatologia", "Otorrinolaringologia", "Pediatria", "Psicologia", "Pneumologia/Tisiologia", "Proctologia", "Psiquiatria", "Reumatologia", "Urologia", "Neurocirurgia" }));

        lblEspecialidade.setText("Especialidade");

        lblEstadoCivil1.setText("Estado civil");

        lblTelefone1.setText("Telefone");

        lblDataNascimento1.setText("Data de nascimento");

        lblcdMedico.setText("Sexo do Medico");

        lblNmMedico.setText("Nome");

        lblCpf1.setText("Cpf");

        lblCRM.setText("CRM");

        lbMedicos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMedicos.setText("Medicos");

        lblSnMedico.setText("Sobrenome");

        javax.swing.GroupLayout pnMedicoLayout = new javax.swing.GroupLayout(pnMedico);
        pnMedico.setLayout(pnMedicoLayout);
        pnMedicoLayout.setHorizontalGroup(
            pnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMedicoLayout.createSequentialGroup()
                        .addGroup(pnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMedicoLayout.createSequentialGroup()
                                .addComponent(tfSexoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(pnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNmMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNmMedico))
                                .addGap(18, 18, 18)
                                .addGroup(pnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnMedicoLayout.createSequentialGroup()
                                        .addComponent(tfSnMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tffCpfMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblSnMedico))
                                .addGap(18, 18, 18)
                                .addComponent(tftCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnMedicoLayout.createSequentialGroup()
                                .addGroup(pnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnMedicoLayout.createSequentialGroup()
                                        .addComponent(lblDataNascimento1)
                                        .addGap(57, 57, 57)
                                        .addComponent(lblTelefone1)
                                        .addGap(78, 78, 78)
                                        .addComponent(lblEstadoCivil1))
                                    .addGroup(pnMedicoLayout.createSequentialGroup()
                                        .addComponent(tffDtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tffTelefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbEstadoCivilMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addGroup(pnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEspecialidade))))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(pnMedicoLayout.createSequentialGroup()
                        .addComponent(lblcdMedico)
                        .addGap(322, 322, 322)
                        .addComponent(lblCpf1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCRM)
                        .addGap(76, 76, 76))))
            .addGroup(pnMedicoLayout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(lbMedicos)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnMedicoLayout.setVerticalGroup(
            pnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMedicoLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lbMedicos)
                .addGap(18, 18, 18)
                .addGroup(pnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcdMedico)
                    .addComponent(lblNmMedico)
                    .addComponent(lblCpf1)
                    .addComponent(lblCRM)
                    .addComponent(lblSnMedico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSexoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tffCpfMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNmMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftCRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSnMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascimento1)
                    .addComponent(lblTelefone1)
                    .addComponent(lblEstadoCivil1)
                    .addComponent(lblEspecialidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tffDtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tffTelefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstadoCivilMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbCadastros.addTab("Medicos", pnMedico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(381, 381, 381)
                                .addComponent(btnCadastrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tbCadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbCadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnLimpar))
                .addContainerGap())
        );

        tbCadastros.getAccessibleContext().setAccessibleName("Pacientes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        
        if (tbCadastros.getSelectedComponent()==pnPaciente) registrarPaciente();
            
         else if (tbCadastros.getSelectedComponent()==pnMedico) registrarMedico();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        
        if (tbCadastros.getSelectedComponent()==pnPaciente) LimpaPaciente();
            
         else if (tbCadastros.getSelectedComponent()==pnMedico) LimpaMed();
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbConvenio;
    private javax.swing.JComboBox<String> cbEspecialidade;
    private javax.swing.JComboBox<String> cbEstadoCivil;
    private javax.swing.JComboBox<String> cbEstadoCivilMedico;
    private javax.swing.JLabel lbMedicos;
    private javax.swing.JLabel lbPacientes;
    private javax.swing.JLabel lblCRM;
    private javax.swing.JLabel lblConvenio;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCpf1;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblDataNascimento1;
    private javax.swing.JLabel lblEspecialidade;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblEstadoCivil1;
    private javax.swing.JLabel lblNmMedico;
    private javax.swing.JLabel lblNmPaciente;
    private javax.swing.JLabel lblSexoPaciente;
    private javax.swing.JLabel lblSnMedico;
    private javax.swing.JLabel lblSnPaciente;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTelefone1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblcdMedico;
    private javax.swing.JPanel pnMedico;
    private javax.swing.JPanel pnPaciente;
    private javax.swing.JTabbedPane tbCadastros;
    private javax.swing.JTextField tfNmMedico;
    private javax.swing.JTextField tfNmPaciente;
    private javax.swing.JTextField tfSexoMedico;
    private javax.swing.JTextField tfSexoPaciente;
    private javax.swing.JTextField tfSnMedico;
    private javax.swing.JTextField tfSnPaciente;
    private javax.swing.JFormattedTextField tffCpf;
    private javax.swing.JFormattedTextField tffCpfMedico;
    private javax.swing.JFormattedTextField tffDtMedico;
    private javax.swing.JFormattedTextField tffDtPaciente;
    private javax.swing.JFormattedTextField tffTelefoneMedico;
    private javax.swing.JFormattedTextField tffTelefonePaciente;
    private javax.swing.JFormattedTextField tftCRM;
    // End of variables declaration//GEN-END:variables
}
