package View;

import java.awt.Dimension;
import java.awt.Toolkit;
import util.Botoes;

public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        centralizarComponente();
    }
    
    public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblbPaciente = new javax.swing.JLabel();
        lblbPacienteTxt = new javax.swing.JLabel();
        lblbConsulta = new javax.swing.JLabel();
        lblbConsultaTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MedSys");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bem vindo");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblbPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Team_50px.png"))); // NOI18N
        lblbPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbPacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbPacienteMouseExited(evt);
            }
        });

        lblbPacienteTxt.setText("Cadastros");

        lblbConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Test_Passed_50px.png"))); // NOI18N
        lblbConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbConsultaMouseExited(evt);
            }
        });

        lblbConsultaTxt.setText("Consultas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbPaciente)
                    .addComponent(lblbPacienteTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbConsulta)
                    .addComponent(lblbConsultaTxt))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblbPaciente)
                    .addComponent(lblbConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbPacienteTxt)
                    .addComponent(lblbConsultaTxt))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblbPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbPacienteMouseClicked
        // TODO add your handling code here:
        Cadastros p = new Cadastros();
        p.setVisible(true);
    }//GEN-LAST:event_lblbPacienteMouseClicked

    private void lblbConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbConsultaMouseClicked
        // TODO add your handling code here:
        TelaConsultas t = new TelaConsultas();
        t.setVisible(true);
    }//GEN-LAST:event_lblbConsultaMouseClicked

    private void lblbPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbPacienteMouseEntered
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.botabotão(lblbPaciente);
    }//GEN-LAST:event_lblbPacienteMouseEntered

    private void lblbPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbPacienteMouseExited
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.tirabotão(lblbPaciente);
    }//GEN-LAST:event_lblbPacienteMouseExited

    private void lblbConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbConsultaMouseEntered
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.botabotão(lblbConsulta);
    }//GEN-LAST:event_lblbConsultaMouseEntered

    private void lblbConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbConsultaMouseExited
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.tirabotão(lblbConsulta);
    }//GEN-LAST:event_lblbConsultaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblbConsulta;
    private javax.swing.JLabel lblbConsultaTxt;
    private javax.swing.JLabel lblbPaciente;
    private javax.swing.JLabel lblbPacienteTxt;
    // End of variables declaration//GEN-END:variables
}
