/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;
import util.Botoes;

/**
 *
 * @author lucas
 */
public class InterfaceMedico extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceMedico
     */
    public InterfaceMedico() {
        initComponents();
        centralizarComponente();
    }
    
        public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigoPaciente = new javax.swing.JLabel();
        lblCpfPaciente = new javax.swing.JLabel();
        lblNomePaciente = new javax.swing.JLabel();
        lblCodigoPacientedf = new javax.swing.JLabel();
        lblCpfPacientedf = new javax.swing.JLabel();
        lblNomePacinetedf = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblConsulta = new javax.swing.JLabel();
        lblNomeMedico = new javax.swing.JLabel();
        lblNomeMedicodf = new javax.swing.JLabel();
        lblQueixaDescritivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taQueixaDescritivo = new javax.swing.JTextArea();
        lblLaudoMedico = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taLaudoMedico = new javax.swing.JTextArea();
        lblSolicitacãoExame = new javax.swing.JLabel();
        cbSolicitacaoExame = new javax.swing.JComboBox<>();
        lblSidDoenca = new javax.swing.JLabel();
        cbSidDoenca = new javax.swing.JComboBox<>();
        lblObservacão = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taObservacao = new javax.swing.JTextArea();
        lblbConfirmaConsulta = new javax.swing.JLabel();
        lblEncaminhar = new javax.swing.JLabel();
        cbEncaminhar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta");

        lblCodigoPaciente.setText("Codigo");

        lblCpfPaciente.setText("Cpf");

        lblNomePaciente.setText("Nome do paciente");

        lblCodigoPacientedf.setText("--");

        lblCpfPacientedf.setText("--");

        lblNomePacinetedf.setText("---");

        lblConsulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblConsulta.setText("Consulta");

        lblNomeMedico.setText("Medico");

        lblNomeMedicodf.setText("--");

        lblQueixaDescritivo.setText("Queixa / Descritivo");

        taQueixaDescritivo.setColumns(20);
        taQueixaDescritivo.setRows(5);
        jScrollPane1.setViewportView(taQueixaDescritivo);

        lblLaudoMedico.setText("Laudo Medico");

        taLaudoMedico.setColumns(20);
        taLaudoMedico.setRows(5);
        jScrollPane2.setViewportView(taLaudoMedico);

        lblSolicitacãoExame.setText("Solicitação de exame:");

        cbSolicitacaoExame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSidDoenca.setText("SID / Doença:");

        cbSidDoenca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblObservacão.setText("Observação");

        taObservacao.setColumns(20);
        taObservacao.setRows(5);
        jScrollPane3.setViewportView(taObservacao);

        lblbConfirmaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Inspection_50px.png"))); // NOI18N
        lblbConfirmaConsulta.setToolTipText("Concluir Consulta");
        lblbConfirmaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbConfirmaConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbConfirmaConsultaMouseExited(evt);
            }
        });

        lblEncaminhar.setText("Encaminhar:");

        cbEncaminhar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSolicitacãoExame)
                            .addComponent(lblSidDoenca)
                            .addComponent(lblEncaminhar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbSolicitacaoExame, 0, 106, Short.MAX_VALUE)
                            .addComponent(cbSidDoenca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbEncaminhar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigoPaciente)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblCodigoPacientedf)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCpfPaciente)
                                        .addGap(42, 42, 42)
                                        .addComponent(lblNomePaciente))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCpfPacientedf)
                                        .addGap(83, 83, 83)
                                        .addComponent(lblNomePacinetedf))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(lblLaudoMedico)
                                .addGap(201, 201, 201)
                                .addComponent(lblObservacão)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblQueixaDescritivo)
                                .addGap(310, 310, 310))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblNomeMedicodf)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblConsulta)
                                .addGap(225, 225, 225)
                                .addComponent(lblNomeMedico)
                                .addGap(46, 46, 46))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblbConfirmaConsulta)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblConsulta)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoPaciente)
                            .addComponent(lblCpfPaciente)
                            .addComponent(lblNomePaciente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoPacientedf)
                            .addComponent(lblCpfPacientedf)
                            .addComponent(lblNomePacinetedf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblNomeMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNomeMedicodf)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQueixaDescritivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLaudoMedico)
                    .addComponent(lblObservacão))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSolicitacãoExame)
                            .addComponent(cbSolicitacaoExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSidDoenca)
                            .addComponent(cbSidDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncaminhar)
                            .addComponent(cbEncaminhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(11, 11, 11)
                .addComponent(lblbConfirmaConsulta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblbConfirmaConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbConfirmaConsultaMouseEntered
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.botabotão(lblbConfirmaConsulta);
    }//GEN-LAST:event_lblbConfirmaConsultaMouseEntered

    private void lblbConfirmaConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbConfirmaConsultaMouseExited
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.tirabotão(lblbConfirmaConsulta);
    }//GEN-LAST:event_lblbConfirmaConsultaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEncaminhar;
    private javax.swing.JComboBox<String> cbSidDoenca;
    private javax.swing.JComboBox<String> cbSolicitacaoExame;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCodigoPaciente;
    private javax.swing.JLabel lblCodigoPacientedf;
    private javax.swing.JLabel lblConsulta;
    private javax.swing.JLabel lblCpfPaciente;
    private javax.swing.JLabel lblCpfPacientedf;
    private javax.swing.JLabel lblEncaminhar;
    private javax.swing.JLabel lblLaudoMedico;
    private javax.swing.JLabel lblNomeMedico;
    private javax.swing.JLabel lblNomeMedicodf;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JLabel lblNomePacinetedf;
    private javax.swing.JLabel lblObservacão;
    private javax.swing.JLabel lblQueixaDescritivo;
    private javax.swing.JLabel lblSidDoenca;
    private javax.swing.JLabel lblSolicitacãoExame;
    private javax.swing.JLabel lblbConfirmaConsulta;
    private javax.swing.JTextArea taLaudoMedico;
    private javax.swing.JTextArea taObservacao;
    private javax.swing.JTextArea taQueixaDescritivo;
    // End of variables declaration//GEN-END:variables
}
