package View;

import Model.Consulta;
import java.awt.Dimension;
import java.awt.Toolkit;
import util.Botoes;

public class TelaConsultas extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultas
     */
    
    private String codigoConsulta;
    private String status;
    private String dataConsulta;
    private String laudoMedico;
    private String medicoNome;
    private String pacienteNome;

    /**
     * Preenche a table de consultas tanto abertas quanto fechadas com as consultas presentes na base de dados
     */
    public void setTable(){

        Consulta con = new Consulta(codigoConsulta,status,dataConsulta,laudoMedico,medicoNome,pacienteNome);
        
        tbConsultaAberta.setModel(con.TableConsulta());
        tbConsultasBaixadas.setModel(con.CFechado());
        
        

    }
    
    public TelaConsultas() {
        initComponents();
        setTable();
        centralizarComponente();
        lblSelectConsulta.setVisible(false);
    }
     /**
     *Centraliza a view na tela do usuario
      */
    public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
    /**
     * Utilizado para quando o medico iniciar a tela não tenha acesso aos botoes de criar e excluir consultas, pois é uma função do operador.
     */
    public void Medico(){
        lblNovaConsulta.setVisible(false);
        lblCancelaConsulta.setVisible(false);
        lblSelectConsulta.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpConsultas = new javax.swing.JTabbedPane();
        spAbertas = new javax.swing.JScrollPane();
        tbConsultaAberta = new javax.swing.JTable();
        pnBaixadas = new javax.swing.JPanel();
        spBaixadas = new javax.swing.JScrollPane();
        tbConsultasBaixadas = new javax.swing.JTable();
        lblCancelar = new javax.swing.JLabel();
        lblConsultas = new javax.swing.JLabel();
        lblCancelaConsulta = new javax.swing.JLabel();
        lblNovaConsulta = new javax.swing.JLabel();
        lblSelectConsulta = new javax.swing.JLabel();

        setTitle("Consultas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbConsultaAberta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código da Consulta", "Status", "Data da Consulta", "Paciente", "Medico", "SID", "Tipo de Exame"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbConsultaAberta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbConsultaAbertaMouseEntered(evt);
            }
        });
        spAbertas.setViewportView(tbConsultaAberta);
        if (tbConsultaAberta.getColumnModel().getColumnCount() > 0) {
            tbConsultaAberta.getColumnModel().getColumn(0).setResizable(false);
            tbConsultaAberta.getColumnModel().getColumn(1).setResizable(false);
            tbConsultaAberta.getColumnModel().getColumn(2).setResizable(false);
            tbConsultaAberta.getColumnModel().getColumn(3).setResizable(false);
            tbConsultaAberta.getColumnModel().getColumn(4).setResizable(false);
            tbConsultaAberta.getColumnModel().getColumn(5).setResizable(false);
            tbConsultaAberta.getColumnModel().getColumn(6).setResizable(false);
        }

        jtpConsultas.addTab("Abertas", spAbertas);

        tbConsultasBaixadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spBaixadas.setViewportView(tbConsultasBaixadas);

        javax.swing.GroupLayout pnBaixadasLayout = new javax.swing.GroupLayout(pnBaixadas);
        pnBaixadas.setLayout(pnBaixadasLayout);
        pnBaixadasLayout.setHorizontalGroup(
            pnBaixadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spBaixadas, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
        pnBaixadasLayout.setVerticalGroup(
            pnBaixadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spBaixadas, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );

        jtpConsultas.addTab("Baixadas", pnBaixadas);

        getContentPane().add(jtpConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, -1, 202));

        lblCancelar.setToolTipText("");
        getContentPane().add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 366, -1, -1));

        lblConsultas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblConsultas.setText("Consultas");
        getContentPane().add(lblConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 11, -1, 31));

        lblCancelaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Delete_File_50px.png"))); // NOI18N
        lblCancelaConsulta.setToolTipText("Cancelar Consulta");
        lblCancelaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelaConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelaConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelaConsultaMouseExited(evt);
            }
        });
        getContentPane().add(lblCancelaConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 281, -1, -1));

        lblNovaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_New_File_50px.png"))); // NOI18N
        lblNovaConsulta.setToolTipText("Nova Consulta");
        lblNovaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNovaConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNovaConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNovaConsultaMouseExited(evt);
            }
        });
        getContentPane().add(lblNovaConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 281, -1, -1));

        lblSelectConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Inspection_50px.png"))); // NOI18N
        lblSelectConsulta.setToolTipText("Selecionar consulta");
        lblSelectConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSelectConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSelectConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSelectConsultaMouseExited(evt);
            }
        });
        getContentPane().add(lblSelectConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(877, 281, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNovaConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovaConsultaMouseEntered
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.botabotão(lblNovaConsulta);
    }//GEN-LAST:event_lblNovaConsultaMouseEntered

    private void lblNovaConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovaConsultaMouseExited
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.tirabotão(lblNovaConsulta);
    }//GEN-LAST:event_lblNovaConsultaMouseExited

    private void lblCancelaConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelaConsultaMouseEntered
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.botabotão(lblCancelaConsulta);
    }//GEN-LAST:event_lblCancelaConsultaMouseEntered

    private void lblCancelaConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelaConsultaMouseExited
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.tirabotão(lblCancelaConsulta);
    }//GEN-LAST:event_lblCancelaConsultaMouseExited

    private void lblNovaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovaConsultaMouseClicked
        // TODO add your handling code here:
        TelaConsultaNova tl = new TelaConsultaNova();
        tl.setVisible(true);
    }//GEN-LAST:event_lblNovaConsultaMouseClicked

    private void lblSelectConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelectConsultaMouseClicked
        // TODO add your handling code here:
        int row = tbConsultaAberta.getSelectedRow();
        int[] col = {0,3,4};
        String cd_consulta = tbConsultaAberta.getModel().getValueAt(row, col[0]).toString();
        String nm_pac = tbConsultaAberta.getModel().getValueAt(row, col[1]).toString();
        String nm_med = tbConsultaAberta.getModel().getValueAt(row, col[2]).toString();
        System.out.println(cd_consulta + " " + nm_pac + " " + nm_med);
        InterfaceMedico im = new InterfaceMedico(cd_consulta, nm_pac, nm_med);
        im.setVisible(true);
    }//GEN-LAST:event_lblSelectConsultaMouseClicked

    private void lblSelectConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelectConsultaMouseEntered
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.botabotão(lblSelectConsulta);
    }//GEN-LAST:event_lblSelectConsultaMouseEntered

    private void lblSelectConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelectConsultaMouseExited
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.tirabotão(lblSelectConsulta);
    }//GEN-LAST:event_lblSelectConsultaMouseExited

    private void lblCancelaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelaConsultaMouseClicked
        // TODO add your handling code here:
        int row = tbConsultaAberta.getSelectedRow();
        int col = 0;
        String value = tbConsultaAberta.getModel().getValueAt(row, col).toString();
        Consulta c = new Consulta(value );
         c.excluir();
        setTable();
         //TelaConsultas tc = new TelaConsultas();
        // tc.setVisible(true);
        //TelaConsultas.this.dispose();
    }//GEN-LAST:event_lblCancelaConsultaMouseClicked

    private void tbConsultaAbertaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbConsultaAbertaMouseEntered
        // TODO add your handling code here:
        setTable();
    }//GEN-LAST:event_tbConsultaAbertaMouseEntered

    public void CancelaConsulta(){
        long idFind;
        String cpfFind;
        String nomeFind;
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jtpConsultas;
    private javax.swing.JLabel lblCancelaConsulta;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblConsultas;
    private javax.swing.JLabel lblNovaConsulta;
    private javax.swing.JLabel lblSelectConsulta;
    private javax.swing.JPanel pnBaixadas;
    private javax.swing.JScrollPane spAbertas;
    private javax.swing.JScrollPane spBaixadas;
    private javax.swing.JTable tbConsultaAberta;
    private javax.swing.JTable tbConsultasBaixadas;
    // End of variables declaration//GEN-END:variables
}
