package View;

import Model.Consulta;
import Model.Medico;
import java.awt.Dimension;
import java.awt.Toolkit;
import util.Botoes;

public class TelaConsultaNova extends javax.swing.JFrame {
    
    private void setMedico(){
        Medico med = new Medico();
        for (Medico medico : med.buscar()) {
            cbMedico.addItem(medico.getNome().concat(" "+medico.getSobrenome()));
        }
    }
    
     /*private void registrarConsulta() {


            String nome = tfNmMed.getText();
            String sobrenome = tfSnMed.getText();
            String CRM = tftCRM.getText();
            String CPF = tffCpfMed.getText();
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            String Nascimento = fmt.format(this.dtcDataDeNascimentoMed.getDate());
            String Telefone = TffCelularMed.getText();


		//Consulta cons = new Consulta(Status, DataConsulta, QueixaPaciente, ExameFisico, Conduta, sid, PacienteNome, PacienteSobrenome, MedicoNome, MedicoSobrenome);
                //cons.gravar();
    }*/

    
    /**
     * Creates new form TelaConsultaNova
     */
    public TelaConsultaNova() {
        initComponents();
        centralizarComponente();
        setMedico();
    }
    
    public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbMedico = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblDataDaConsulta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taQueixaDoPaciente = new javax.swing.JTextArea();
        lblQueixaDoPaciente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblbSalvar = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setTitle("Nova Consulta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nova consulta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 11, -1, -1));

        getContentPane().add(cbMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 129, -1));

        jLabel2.setText("Medico");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        lblDataDaConsulta.setText("Data da consulta");
        getContentPane().add(lblDataDaConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        taQueixaDoPaciente.setColumns(20);
        taQueixaDoPaciente.setRows(5);
        jScrollPane1.setViewportView(taQueixaDoPaciente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, 563, -1));

        lblQueixaDoPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQueixaDoPaciente.setText("Queixa do paciente");
        getContentPane().add(lblQueixaDoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 170, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Doctors_Bag_70px.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        lblbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Save_30px.png"))); // NOI18N
        lblbSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbSalvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbSalvarMouseExited(evt);
            }
        });
        getContentPane().add(lblbSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        jLabel5.setText("Paciente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblbSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbSalvarMouseEntered
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.botabotão(lblbSalvar);
    }//GEN-LAST:event_lblbSalvarMouseEntered

    private void lblbSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbSalvarMouseExited
        // TODO add your handling code here:
        Botoes bt = new Botoes();
        bt.tirabotão(lblbSalvar);
    }//GEN-LAST:event_lblbSalvarMouseExited

    private void lblbSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbSalvarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblbSalvarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaNova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaNova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaNova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaNova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaNova().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbMedico;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataDaConsulta;
    private javax.swing.JLabel lblQueixaDoPaciente;
    private javax.swing.JLabel lblbSalvar;
    private javax.swing.JTextArea taQueixaDoPaciente;
    // End of variables declaration//GEN-END:variables
}
